### ISSUE TITLE
ASMS 2018 poster

### ISSUE THREAD

**Issue by tobiasko** [fgcz/rawDiag#19]
INFORMATICS: ALGORITHMS AND STATISTICAL ADVANCES II 374-392
ThP 375
Optimize your Method: rawDiagnostic An R Package to Support Method Development for Bottom-up Proteomics on Orbitrap Instruments

**Comment by tobiasko** [comment]
Printing @ASMS

http://www.asms.org/conferences/annual-conference/presenter-guidelines

**Comment by cpanse** [comment]
<img width="916" alt="screen shot 2018-05-30 at 21 07 13" src="https://user-images.githubusercontent.com/4901987/40742033-7f663bfc-644d-11e8-9075-85d340cb8dd8.png">

**Comment by cpanse** [comment]
http://fgcz-ms.uzh.ch/~cpanse/ASMS2018_ID291250.pdf
