### ISSUE TITLE
installation of NewRawFileReader on MacOS

### ISSUE THREAD

**Issue by tobiasko** [fgcz/rawDiag#23]
I tried to follow

"Register the .Net assembly in your system similar to a Linux installation", but it is unclear to me what this implies. The following things are done:

- downloaded the NewRawFileReader archive from Thermo
- installed mono

What are the next steps? How do I install the NuGet packe? Do I need VisualStudio? If not, what are the alternatives? We need to document this in a way that people without any prior experience in this area will to able to complete installation.

**Comment by tobiasko** [comment]
`tobiasko@public-docking-hpx-1240:~/Downloads/OneDrive_1_14-06-2018/Windows_MacOS > gacutil -i lib/monomac/ThermoFisher.CommonCore.BackgroundSubtraction.dll 
Failure adding assembly lib/monomac/ThermoFisher.CommonCore.BackgroundSubtraction.dll to the cache: Strong name cannot be verified for delay-signed assembly`

**Comment by tobiasko** [comment]
I used strategy 2 as given in the README (copied dlls to exec folder of package). Calling read.raw() gives an error using sample file provided with the package:

> (rawfile <- file.path(path.package(package = 'rawDiag'), 'extdata', 'sample.raw'))
[1] "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rawDiag/extdata/sample.raw"
> system.time(RAW <- read.raw(file = rawfile))
executing mono /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rawDiag/exec/fgcz_raw.exe /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rawDiag/extdata/sample.raw qc ...

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'ThermoFisher.CommonCore.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1aef06afb5abd953' or one of its dependencies.
File name: 'ThermoFisher.CommonCore.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1aef06afb5abd953'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'ThermoFisher.CommonCore.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1aef06afb5abd953' or one of its dependencies.
File name: 'ThermoFisher.CommonCore.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1aef06afb5abd953'
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Timing stopped at: 0.016 0.018 0.116 
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.6

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rawDiag_0.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     bindr_0.1.1      magrittr_1.5     bit_1.1-12       munsell_0.4.3   
 [6] lattice_0.20-35  colorspace_1.3-2 R6_2.2.2         rlang_0.2.0      blob_1.1.1      
[11] plyr_1.8.4       dplyr_0.7.4      tools_3.3.2      parallel_3.3.2   grid_3.3.2      
[16] gtable_0.2.0     DBI_0.8          lazyeval_0.2.1   bit64_0.9-7      assertthat_0.2.0
[21] digest_0.6.15    tibble_1.4.2     bindrcpp_0.2.2   purrr_0.2.4      tidyr_0.8.0     
[26] ggplot2_2.2.1    memoise_1.1.0    glue_1.2.0       RSQLite_2.1.0    pillar_1.2.1    
[31] scales_0.5.0     hexbin_1.27.1    pkgconfig_2.0.1

**Comment by cpanse** [comment]
On how to install the New ThermoRawFileReader follow the guidelines by Thermo.

**Comment by tobiasko** [comment]
@cpanse Your childish behaviour is not helpful! I have read the docs provided by Thermo and I still was not able to complete the installation. Do you believe that the reviewers will be smarter more talented than me?

**Comment by tobiasko** [comment]
btw: I meanwhile found out what happens. The dlls get eliminated, each time the R package gets updated/reinstalled. Now it works:
`
> system.time(RAW <- read.raw(file = rawfile))
executing mono /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rawDiag/exec/fgcz_raw.exe /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rawDiag/extdata/sample.raw qc ...
MasterScanNumber calculated
renamed LMmZCorrectionppm to LMCorrection
renamed AGCPSMode to PrescanMode
   user  system elapsed 
  0.396   0.103   4.829 
Warning message:
In is.rawDiag(object) :
  missing column name(s): MasterScanNumber, LMCorrection, ElapsedScanTimesec, transient, AGCMode, PrescanMode
> (rawfile <- file.path(path.package(package = 'rawDiag'), 'extdata', 'sample.raw'))
[1] "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rawDiag/extdata/sample.raw"
`
