### ISSUE TITLE
Number of precursors scheduled for fragmentation for each MS1 scan

### ISSUE THREAD

**Issue by pisistrato** [fgcz/rawDiag#50]
First of all, rawDiag is AWESOME!
I guess this is more a feature request, but I am not completely sure this is even possible.
It would be nice to be able to extract from a raw file the list of monoisotopic m/z the mass spectrometer has 'calculated' from the MS1 survey scan. I believe Thermo is using a proprietary (?) algorithm for the MIPS, but probably the output of that step (probably m/z, charge and intensity) is stored in the final raw file for each MS1 scan.
Knowing which precursor has been actually fragmented and which one not due to the cycle time, one can decide whether it is worth to adjust LC & MS parameters to dig deeper into the sample.

**Comment by tobiasko** [comment]
Hi pisistrato,

thx for your interest in rawDiag, but I fear we can not help here. To the best of my knowledge the list of potential targets ions is either not stored in the raw file or not accessible through the RawFileReader dll. I guess this list only exists during the instrument run time and lives in memory of the internal orbitrap PC.

Have you checked

[iAPI](https://github.com/thermofisherlsms/iapi)

??? The API allows real time instrument monitoring and control.

Greetings,
Tobi
