### ISSUE TITLE
Cannot find dependency "Spectra"

### ISSUE THREAD

**Issue by joerg-b** [fgcz/rawDiag#64]
When trying to install rawDiag I get this error:

ERROR: dependency ‘Spectra’ is not available for package ‘rawDiag’

I cannot find a package of this name on CRAN or Bioconductor. Where can I get it?

**Comment by BerndMaier** [comment]
Already tried to install like this ?

https://github.com/fgcz/rawDiag/releases

Think I got the same error message with the Version 0.0.36 from another page.

Spectra belongs to:
https://www.rformassspectrometry.org/pkgs/

**Comment by tobiasko** [comment]
Hi @joerg-b,

which version of rawDiag are you using?

Our latest release is [Proteomics Forum 2019](https://github.com/fgcz/rawDiag/releases), or version 0.0.34. This release does not depend on `Spectra`. We hope to compile a new release soon.

Best,
Tobi
